### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by spiegelball** [KexianHust/ViTA#1]
Your results look very good! Are you planning to release the code anytime soon?

**Comment by KexianHust** [comment]
Yes, we will release our code once our paper is accepted. Please stay tuned!

**Comment by zhanghongyong123456** [comment]
When will the code be released? Thank you，Special anticipation test

**Comment by KexianHust** [comment]
Thank you for your interest in our work! We are sitll waiting for the reviews. We'll release the code once our paper is accepted.

**Comment by KexianHust** [comment]
Hi, we have released our code! Please have a try if you are interested.
